#!/bin/sh
#
# Try to undo the fortify / occupy actions
/etc/init.d/apache2 stop
/etc/init.d/trac stop
a2dismod actions auth_digest dav dav_svn expires headers rewrite proxy_http proxy
rm /etc/apache2/mods-enabled/dav_svn.conf
rm /etc/apache2/mods-enabled/proxy.conf
rm /etc/init.d/trac
update-rc.d trac remove
deluser --force --remove-home trac
deluser --force --remove-home svn
chmod o= /var/log/apache2
chmod o= /var/log/apache2/access.log
chmod o= /var/log/apache2/error.log
