#!/bin/sh
FILES=`dirname "$0"`
[ ! -f $FILES/../users ] && echo "Do not run without creating a users file" && exit 0
project_name="${1:=fort}"

svnadmin create root
svn checkout file:///home/svn/root tmp
(cd tmp; svn mkdir trunk tags branches; svn commit -m "Initial repository layout")
rm -rf tmp
