#!/bin/sh
FILES=/home/fort/vmsetup
mkdir etc etc/init.d .userv
cp $FILES/trac/user-init-script etc/init.d/tracd
cp $FILES/trac/user-userv-rc .userv/rc
cp $FILES/trac/user-hook trac-post-commit-hook
chmod 755 trac-post-commit-hook
touch users.htdigest
