#!/bin/bash

### BEGIN INIT INFO
# Provides:          trac
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start trac daemon at boot time
# Description:       Enable service provided by trac daemon.
### END INIT INFO

userv trac init.d/tracd "$@"
